### ISSUE TITLE
Revisión

### ISSUE THREAD

**Issue by EduardoHernandezGuzman** [4GeeksAcademy/pokercard-generator#1]
# Revisión - Aprobado :white_check_mark:
- [x] Estilo de código y limpieza
# Feedback
- Muy buen trabajo @marcoluqueh . Felicitaciones 🥳
## Estilo de código y limpieza
- ¡Buen trabajo!
## Mejores prácticas/comentarios
- Me encanta la implementación del sonido al generar nueva carta.
- Cuidado, al maximizar la ventana del navegador me muestra la carta así 
![Captura de pantalla de 2024-04-09 11-47-08](https://github.com/4GeeksAcademy/pokercard-generator/assets/139759297/77e77cb4-2c8d-42b7-adbb-dc3b95966fee)
- Muy buen trabajo 🎉🎉🎉

**Comment by marcoluqueh** [comment]
¡Planteé lo del sonido como algo curioso que añadir al código y el que encontré era demasiado bueno como para no meterlo! En cuanto a lo del tamaño de pantalla, intentaré modificarlo luego con el col-lg, que aún no tengo demasiado como funciona...

Gracias por las buenas palabras y por la ayuda 😁
